#!/bin/sh
#
#-- remove old configuration files
#
rm -f depcomp missing install-sh mkinstalldirs libtool acconfig.h compile
rm -f configure Makefile.in config.status config.log config.guess config.cache 
rm -f aclocal.m4 ltmain.sh config.sub linomnia.pc
rm -rf m4
rm -rf autom4te.cache Makefile Makefile.in *.lo
rm -rf docs/html
rm -f docs/Makefile.in docs/Makefile
rm -f src/*.o src/*.lo src/Makefile.in src/Makefile src/libomnia.*
rm -f test/*.o test/*.lo test/Makefile.in test/Makefile 
rm -f test/omnia_test_gcflcm test/omnia_test_kiss test/omnia_test_rounding test/omnia_test_trig 
#
#-- end
